### ISSUE TITLE
Zabbix 4.2.1 issue - template does not work

### ISSUE THREAD

**Issue by lamberbee** [MantasTumenas/Zabbix-template-for-Microsoft-Windows-Server#3]
Just activated the template on Zabbix server 4.2.1 and assigned it to a Windows server with Zabbix Agent. Connection wont get active. Switching back to the standard Template OS Windows (Template App Zabbix Agent) the server gets connected again for monitoring.

Is the (Template App Zabbix Agent) missing from this template?

**Comment by MantasTumenas** [comment]
Template App Zabbix Agent is not included in this template. Now, what do you mean "Connection wont get active". Do the items become unsupported? Does Discovery is not working? Does zabbix agent log show any additional information?

**Comment by lamberbee** [comment]
Well, next to the hosts you see availability. When using your templates, it stays grayed out. When I use the Standard Zabbix template like in the example, the availability gets green.

![afbeelding](https://user-images.githubusercontent.com/2265929/58187331-da4ecc00-7cb6-11e9-88c0-93038d02e7e6.png)

**Comment by MantasTumenas** [comment]
It is not a problem... It is how it works.
The ZBX near your host will lit:
Green - You have at least 1 Passive check and connection between Server & Host can be established.
Red - If you have at least 1 Passive check, but your Server/proxy can't establish the connection with the Host
Grey - You have only Active checks or there is no checks at all.

This template has only Active checks, so it will stay Grey https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/22865-host-availability-is-gray-for-agent-for-help
